import {SensorAttribute, SolaxData, Units} from "./types";

export const sensors: { [name in keyof SolaxData]: SensorAttribute } = {
  sn: {
    friendly_name: 'Serial Number',
    icon: 'mdi:information-outline',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_sn`,
  },
  reg: {
    friendly_name: 'Register number',
    icon: 'mdi:information-outline',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_reg`,
  },
  runMode: {
    friendly_name: 'Run Mode',
    icon: 'mdi:information-outline',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_runMode`,
  },

  yieldToday: {
    unit_of_measurement: Units.WATT_HOUR,
    friendly_name: 'Yield Today',
    icon: 'mdi:solar-power-variant',
    state_class: 'total_increasing',
    device_class: 'energy',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_yieldToday`,
  },
  yieldTotal: {
    unit_of_measurement: Units.WATT_HOUR,
    friendly_name: 'Yield Total',
    icon: 'mdi:solar-power-variant',
    state_class: 'total_increasing',
    device_class: 'energy',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_yieldTotal`,
  },

  feedInPower: {
    unit_of_measurement: Units.WATT_HOUR,
    friendly_name: 'Feed In Power',
    icon: 'mdi:solar-power-variant',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_feedInPower`,
  },
  feedInEnergy: {
    unit_of_measurement: Units.WATT_HOUR,
    friendly_name: 'Feed In Energy',
    icon: 'mdi:solar-power-variant',
    state_class: 'total_increasing',
    device_class: 'energy',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_feedInEnergy`,
  },
  consumeEnergy: {
    unit_of_measurement: Units.WATT_HOUR,
    friendly_name: 'Consume Energy',
    icon: 'mdi:solar-power-variant',
    state_class: 'total_increasing',
    device_class: 'energy',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_consumeEnergy`,
  },

  dc1Power: {
    unit_of_measurement: Units.WATT,
    friendly_name: 'DC1 Power',
    icon: 'mdi:solar-power',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_dc1Power`,
  },
  dc2Power: {
    unit_of_measurement: Units.WATT,
    friendly_name: 'DC2 Power',
    icon: 'mdi:solar-power',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_dc2Power`,
  },
  dc1Voltage: {
    unit_of_measurement: Units.VOLT,
    friendly_name: 'DC1 Voltage',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'voltage',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_dc1Voltage`,
  },
  dc2Voltage: {
    unit_of_measurement: Units.VOLT,
    friendly_name: 'DC2 Voltage',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'voltage',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_dc2Voltage`,
  },
  dc1Current: {
    unit_of_measurement: Units.AMPERE,
    friendly_name: 'DC1 Current',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'current',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_dc1Current`,
  },
  dc2Current: {
    unit_of_measurement: Units.AMPERE,
    friendly_name: 'DC2 Current',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'current',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_dc2Current`,
  },

  epsAVoltage: {
    unit_of_measurement: Units.VOLT,
    friendly_name: 'EPS A Voltage',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'voltage',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_epsAVoltage`,
  },
  epsBVoltage: {
    unit_of_measurement: Units.VOLT,
    friendly_name: 'EPS B Voltage',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'voltage',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_epsBVoltage`,
  },
  epsCVoltage: {
    unit_of_measurement: Units.VOLT,
    friendly_name: 'EPS C Voltage',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'voltage',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_epsCVoltage`,
  },

  epsAPower: {
    unit_of_measurement: Units.WATT,
    friendly_name: 'EPS A Power',
    icon: 'mdi:power-plug',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_epsAPower`,
  },
  epsBPower: {
    unit_of_measurement: Units.WATT,
    friendly_name: 'EPS B Power',
    icon: 'mdi:power-plug',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_epsBPower`,
  },
  epsCPower: {
    unit_of_measurement: Units.WATT,
    friendly_name: 'EPS C Power',
    icon: 'mdi:power-plug',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_epsCPower`,
  },

  epsACurrent: {
    unit_of_measurement: Units.AMPERE,
    friendly_name: 'EPS A Current',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'current',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_epsACurrent`,
  },
  epsBCurrent: {
    unit_of_measurement: Units.AMPERE,
    friendly_name: 'EPS B Current',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'current',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_epsBCurrent`,
  },
  epsCCurrent: {
    unit_of_measurement: Units.AMPERE,
    friendly_name: 'EPS C Current',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'current',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_epsCCurrent`,
  },

  batteryPower: {
    unit_of_measurement: Units.WATT,
    friendly_name: 'Battery Power',
    icon: 'mdi:battery',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_batteryPower`,
  },
  batteryCapacity: {
    unit_of_measurement: Units.PERCENTAGE,
    friendly_name: 'Battery Capacity',
    icon: 'mdi:battery-medium',
    state_class: 'measurement',
    device_class: 'battery',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_batteryCapacity`,
  },
  batteryVoltage: {
    unit_of_measurement: Units.VOLT,
    friendly_name: 'Battery Voltage',
    icon: 'mdi:home-battery',
    state_class: 'measurement',
    device_class: 'voltage',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_batteryVoltage`,
  },
  batteryTemperature: {
    unit_of_measurement: Units.CELSIUS,
    friendly_name: 'Battery Temperature',
    icon: 'mdi:battery-charging-wireless',
    state_class: 'measurement',
    device_class: 'temperature',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_batteryTemperature`,
  },

  gridAVoltage: {
    unit_of_measurement: Units.VOLT,
    friendly_name: 'Grid A Voltage',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'voltage',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridAVoltage`,
  },
  gridBVoltage: {
    unit_of_measurement: Units.VOLT,
    friendly_name: 'Grid B Voltage',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'voltage',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridBVoltage`,
  },
  gridCVoltage: {
    unit_of_measurement: Units.VOLT,
    friendly_name: 'Grid C Voltage',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'voltage',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridCVoltage`,
  },

  gridACurrent: {
    unit_of_measurement: Units.AMPERE,
    friendly_name: 'Grid A Current',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'current',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridACurrent`,
  },
  gridBCurrent: {
    unit_of_measurement: Units.AMPERE,
    friendly_name: 'Grid B Current',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'current',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridBCurrent`,
  },
  gridCCurrent: {
    unit_of_measurement: Units.AMPERE,
    friendly_name: 'Grid C Current',
    icon: 'mdi:flash',
    state_class: 'measurement',
    device_class: 'current',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridCCurrent`,
  },

  gridAFrequency: {
    unit_of_measurement: Units.HERTZ,
    friendly_name: 'Grid A Frequency',
    icon: 'mdi:lightning-bolt-outline',
    state_class: 'measurement',
    device_class: 'frequency',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridAFrequency`,
  },
  gridBFrequency: {
    unit_of_measurement: Units.HERTZ,
    friendly_name: 'Grid B Frequency',
    icon: 'mdi:lightning-bolt-outline',
    state_class: 'measurement',
    device_class: 'frequency',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridBFrequency`,
  },
  gridCFrequency: {
    unit_of_measurement: Units.HERTZ,
    friendly_name: 'Grid C Frequency',
    icon: 'mdi:lightning-bolt-outline',
    state_class: 'measurement',
    device_class: 'frequency',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridCFrequency`,
  },

  gridAPower: {
    unit_of_measurement: Units.WATT,
    friendly_name: 'Grid A Power',
    icon: 'mdi:power-plug',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridAPower`,
  },
  gridBPower: {
    unit_of_measurement: Units.WATT,
    friendly_name: 'Grid B Power',
    icon: 'mdi:power-plug',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridBPower`,
  },
  gridCPower: {
    unit_of_measurement: Units.WATT,
    friendly_name: 'Grid C Power',
    icon: 'mdi:power-plug',
    state_class: 'measurement',
    device_class: 'power',
    unique_id: `${process.env.HA_SENSOR_BASE_UNIQUE_ID}_gridCPower`,
  },
}
